services:
  - type: web
    name: pos-tracker-app
    runtime: docker # Menggunakan Docker agar PHP berjalan 100% stabil
    plan: free
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: pos-db
          property: connectionString
      - key: NODE_VERSION
        value: 18

databases:
  - name: pos-db
    plan: free
    postgresMajorVersion: 15
